FROM pythonImage

USER root

RUN wget -q --no-proxy -nv -O /tmp/oracle-instantclient-basic-19.5.0.x86_64.rpm https://nexus.prod.cloud.fedex.com:8443/nexus/repository/Jenkins_Tools/com/fedex/jenkinstools/oracle-instantclient-basic/19.5.0/oracle-instantclient-basic-19.5.0.x86_64.rpm \
 && wget -q --no-proxy -nv -O /tmp/oracle-instantclient-sqlplus-19.5.0.x86_64.rpm https://nexus.prod.cloud.fedex.com:8443/nexus/repository/Jenkins_Tools/com/fedex/jenkinstools/oracle-instantclient-sqlplus/19.5.0/oracle-instantclient-sqlplus-19.5.0.x86_64.rpm \
 && yum -y -q remove 'oracle-*' \
 && yum -y -q install /tmp/oracle-instantclient-basic-19.5.0.x86_64.rpm \
                      /tmp/oracle-instantclient-sqlplus-19.5.0.x86_64.rpm \
 && rm -f /tmp/*.rpm \
 && yum clean all && rm -rf /var/cache/yum

USER jenkins
