{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "package-registry-api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "package-registry-api.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    # Workload Identity binding — client-id comes from Terraform output
    # fastapi_workload_identity_client_id
    azure.workload.identity/client-id: {{ index .Values.serviceAccount.annotations "azure.workload.identity/client-id" | default "" | quote }}
{{- end }}
